FLASK_CRUDS_SQL/asset/models.py
from tokenize import String
from run import db 
from datetime import datetime
#app/asset/models.py

class Freight(db.Model):
    __tablename__='freight'

    id = db.Column(db.Integer, primary_key=True)
    todays_date = db.Column(db.DateTime)
    notes = db.Column(db.String(100))
    revenue = db.Column(db.Float, nullable=False)
    brokerage = db.Column(db.String(100), nullable=False, index=True)
    driver = db.Column(db.String(100))
    commodity = db.Column(db.String(100))
    weight = db.Column(db.Float(100))
    pickup_date = db.Column(db.DateTime)
    end_date = db.Column(db.DateTime)
    mileage = db.Column(db.Float(100))
    status = db.Column(db.String(50))

    def __init__(self, todays_date, id, notes, revenue, brokerage, driver, commodity, weight, pickup_date, end_date, mileage, status):
            self.id= id
            self.todays_date = todays_date
            self.notes =notes
            self.revenue = revenue
            self.brokerage = brokerage
            self.driver = driver
            self.commodity = commodity
            self.weight = weight
            self.pickup_date = pickup_date 
            self.end_date = end_date
            self.mileage = mileage
            self.status = status


            
    def __repr__(self):
        return '{} by {} for {}'.format(self.id, self.brokerage, self.revenue)

#either change this to brokerage or something class asset 


class Asset(db.Model):
    __tablename__ = 'assets'

    id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.String(100), nullable=False)
    asset_name = db.Column(db.String(100), nullable=False, index=True)

    def __init__(self, type, asset_name):
        self.type = type
        self.asset_name = asset_name

    def __repr__(self):
        return self.asset_name



class Brokerages(db.Model):
    __tablename__='brokerages'

    id = db.Column(db.Integer, primary_key=True)
    brokerage_name =db.Column(db.String(100), nullable=False)

    def __init__(self, brokerage_name):
        self.brokerage_name = brokerage_name

    
    def __repr__(self):
        return self.brokerage_name

FLASK_CRUDS_SQL/asset/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField, SelectField, ValidationError
from wtforms.validators import DataRequired
from wtforms.fields.html5 import DateField
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from asset.models import Asset


def check_if_asset_exist(form, field):
    asset = Asset.query.filter_by(asset_name=field.data).first()
    if asset:
        raise ValidationError('Asset Already Exists')


def get_assets():
    return Asset.query.all()


class EditTransactionForm(FlaskForm):
    type = StringField('Type', render_kw={'readonly': True})
    asset_name = StringField('Asset Name', render_kw={'readonly': True})
    person_name = StringField('Person', render_kw={'readonly': True})
    start_time = DateField('Start Time', render_kw={'readonly': True})
    # end_time = DateField('End Time', validators=[DataRequired()])
    end_time = DateField('End Time', format='%Y-%m-%d', validators=[DataRequired()])
    status = SelectField('Status', choices=[('In Use', 'In Use'), ('In Store', 'In Store')],
                         validators=[DataRequired()])
    submit = SubmitField('Update')


class AddTransactionForm(FlaskForm):
    type = SelectField('Type', validators=[DataRequired()],
                       choices=[('harddisk', 'Hard Disk'), ('testingcard', 'Card')])
    asset_name = QuerySelectField(label='Asset Name', validators=[DataRequired()], query_factory=get_assets,
                                  allow_blank=True)
    person_name = StringField('Person', validators=[DataRequired()])
    start_time = DateField('Start Time', format='%Y-%m-%d', validators=[DataRequired()])
    #start_time = DateField('Start Time', format='%m/%d/%y', render_kw={'placeholder': '6/20/15 for June 20, 2015'})
    end_time = HiddenField('End Time')
    status = SelectField('Status', validators=[DataRequired()], choices=[('In Use', 'In Use')])
    submit = SubmitField('Add')


class AddAssetForm(FlaskForm):
    type = SelectField('Type', validators=[DataRequired()],
                       choices=[('harddisk', 'Hard Disk'),
                                ('testingcard', 'Card')])
    asset_name = StringField('Asset Name', validators=[DataRequired(), check_if_asset_exist])
    submit = SubmitField('Register')

FLASK_CRUDS_SQL/asset/__init__.py

from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

from asset import *

FLASK_CRUDS_SQL/asset/routes.py
from flask_login import login_required
from asset.forms import AddTransactionForm, EditTransactionForm, AddAssetForm
from asset import *
from asset.models import Transaction, Asset
from flask import render_template, flash, request, redirect, url_for
from run import db



@main.route('/')
def display_transactions():
    transactions = Transaction.query.all()
    return render_template('home.html', transactions=transactions)


@main.route('/register/asset', methods=['GET', 'POST'])
@login_required
def add_asset():
    form = AddAssetForm()
    if form.validate_on_submit():
        asset = Asset(type=form.type.data, asset_name=form.asset_name.data)
        db.session.add(asset)
        db.session.commit()
        flash('Asset registered successfully')
        return redirect(url_for('main.display_transactions'))
    return render_template('add_asset.html', form=form)


@main.route('/add/transaction', methods=['GET', 'POST'])
@login_required
def add_transaction():
    form = AddTransactionForm()
    if form.validate_on_submit():
        transaction = Transaction(type=form.type.data, asset_name=str(form.asset_name.data), person_name=form.person_name.data,
                    start_time=form.start_time.data, end_time=None, status=form.status.data)
        db.session.add(transaction)
        db.session.commit()
        flash('Asset added successfully')
        return redirect(url_for('main.display_transactions'))
    return render_template('add_transaction.html', form=form)


@main.route('/edit/transaction/<id>', methods=['GET', 'POST'])
@login_required
def edit_transaction(id):
    transaction = Transaction.query.get(id)
    form = EditTransactionForm(obj=transaction)
    if form.validate_on_submit():
        transaction.end_time = form.end_time.data
        transaction.status = form.status.data
        db.session.add(transaction)
        db.session.commit()
        flash('Edit successful')
        return redirect(url_for('main.display_transactions'))
    return render_template('edit_transaction.html', form=form, id=id)

FLASK_CRUDS_SQL/asset/templates/add_asset.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block body %}
<div class="container">
    <h4 style="margin-left: 45px"> Register new Asset </h4>
    <hr>
    {{ form.hidden_tag() }}
    {{ render_form(form)}}
</div>

{% endblock %}

FLASK_CRUDS_SQL/asset/templates/add_transaction.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block content %}
    <div class="container">
        <h4 style="margin-left: 45px"> Add a new Asset </h4>
        <hr>
          {{ form.hidden_tag() }}
          {{ render_form(form) }}
    </div>
{% endblock %}

FLASK_CRUDS_SQL/asset/templates/edit_transaction.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}


{% block content %}
    <div class="container">
        <h4 style="margin-left: 45px"> Edit Asset </h4>
        <hr>
          {{ form.hidden_tag() }}
          {{ render_form(form) }}
    </div>
{% endblock %}

FLASK_CRUDS_SQL/asset/templates/home.html
{% extends "bootstrap/base.html" %}


{% block body %}

<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 my-2">
            <div class="shadow-lg rounded card text-left">
                <div class="card-body bg-light">
                    <b>Register new Asset</b>
                    <a href="{{ url_for('main.add_asset') }}" class="btn btn-info pull-right">Register</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 my-2">
            <div class="shadow-lg rounded card text-left">
                <div class="card-body bg-light">
                    <b>Add new Request</b>
                    <a href="{{ url_for('main.add_transaction') }}" class="btn btn-info pull-right">Add</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col my-2">
            <h6 class="font-weight-bold">View / Edit existing Requests</h6>
        </div>
        <div class="col col-md-12 my-2">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead class="thead-light">
                        <tr style="background-color: #77f880;">
                            <th> ID</th>
                            <th> Revenue</th>
                            <th> Brokerage</th>
                            <th> Driver</th>
                            <th> Pick-up Date</th>
                            <th> End Date</th>
                            <th> Status</th>
                            <th> Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for transaction in transactions %}
                    <tr>
                        <td> {{ transaction.id }}</td>
                        <td><img src="" alt="asset-img" height="30" width="30"></td>
                        <td> {{ transaction.asset_name }}</td>
                        <td> {{ transaction.person_name }}</td>
                        <td> {{ transaction.start_time }}</td>
                        <td> {{ transaction.end_time }}</td>
                        <td> {% if transaction.status == 'In Use' %}
                            <span class="badge badge-warning">Using</span>
                            {% else %}
                            <span class="badge badge-success">Store</span>
                            {% endif %}
                        </td>
                        <td>
                            <a class="btn btn-light btn-sm"
                            href="{{ url_for('main.edit_transaction', id=transaction.id) }}"
                            role="button">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

FLASK_CRUDS_SQL/templates/base.html
<!DOCTYPE html>
<html lang="en">


{# head #}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Asset Freight Tracker"/>
    <meta name="author" content="Jim M"/>
    <title>Asset Freight Tracker</title>

    <title>{% block title %} {% endblock %}</title>
    {% block styles %}
    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/styles.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='static\css\styles.css') }}">

    {% endblock %}



</head>

{# body #}
    <body>

        <div class="content">
            {# navigation bar #}
            {% block navbar %}
            <nav class="navbar navbar-expand-lg navbar-dark sticky-top py-4">
                <div class="container">
                    <a href="{{ url_for('main.display_transactions') }}" class="navbar-brand"><span
                    class="navbar-brand"><span
                            class="title">Asset Tracker</span> <i class="fas fa-database" style="padding: 3px"></i></a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a href="{{ url_for('main.display_transactions') }}" class="nav-link"> Home </a>
                            </li>
                            <li class="nav-item">
                                <a href="" class="nav-link">
                                    Register </a>
                            </li>
                            {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a href=" {{ url_for('authentication.do_logout') }} " class="nav-item nav-link"> LogOut </a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a href=" {{ url_for('authentication.do_login') }} " class="nav-item nav-link"> LogIn </a>
                            </li>
                            {% endif %}
                            <li class="nav-item">
                                <a href="" class="nav-item nav-link">
                                    {% if current_user.is_authenticated %}
                                    Logged In as {{ current_user.user_name.title() }}
                                    {% else %}
                                    Not Logged In
                                    {% endif %}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>


   {% block body %} 
   
   {% endblock %}

   
{# flash messaging #}
<div class="container my-2">
    <div class="row">
        <div class="col">
            {% for message in get_flashed_messages() %}
            <div class=" container alert alert-info my-flash-class">
                <button type="button" class="close" data-dismiss="alert"></button>
                {{ message }}
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{# empty block for custom content #}
{% block content %} {% endblock content %}
<div class="spacer"></div>

{% block footer %}
<footer class="footer">
    <div class="container text-center">
        <a target="_blank" href="https://www.linkedin.com/in/jim-morales-41409a23a"><i
                class="fab fa-github fa-lg contact-icon"></i></a>
        <a target="_blank" href="https://www.linkedin.com/in/jim-morales-41409a23a"><i
                class="fab fa-linkedin fa-lg contact-icon"></i></a>
    </div>
    <div class="container text-center">
        <small>Made with ❤️ by <a href="https://www.linkedin.com/in/jim-morales-41409a23a/">Jim
            Morales</a></small>
    </div>
</footer>

{% endblock %}


{# optional scripts #}
{% block scripts %}

<!-- Optional JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/5f3f547070.js" crossorigin="anonymous"></script>
<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>

{{ bootstrap.load_js() }}
{% endblock %}

    </body>
</html>